apiVersion: v1
kind: Service
metadata:
  name: nssf
  namespace: open5gs
spec:
  selector:
    app: nssf
  ports:
  - name: sbi
    protocol: TCP
    port: 7777
    targetPort: 7777
  type: ClusterIP
