apiVersion: apps/v1
kind: Deployment

metadata:
  name: upf
  namespace: open5gs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: upf

  template:
    metadata:
      labels:
        app: upf

    spec:
      containers:

      - name: upf
        image: open5gs-upf:latest
        imagePullPolicy: Never

        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN

        volumeMounts:
        - name: tun
          mountPath: /dev/net/tun

      volumes:
      - name: tun
        hostPath:
          path: /dev/net/tun
